# Generated by Drydock — arm64 bun SSR image (prisma) from ./apps/web.
FROM oven/bun:1.3-alpine AS build
WORKDIR /app/apps/web
COPY apps/web/package.json apps/web/bun.lock ./
COPY apps/web/prisma ./prisma
COPY apps/web/prisma.config.ts* ./
ENV DATABASE_URL="postgresql://build:build@127.0.0.1:5432/build"
RUN bun install --frozen-lockfile
WORKDIR /app
COPY . .
WORKDIR /app/apps/web
RUN cd ../.. && bun install --frozen-lockfile && bun run build:hosted && cd apps/web && bun run build

FROM oven/bun:1.3-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app /app
WORKDIR /app/apps/web
EXPOSE 3000
CMD ["sh", "-c", "bun run start"]
