import { PaperCard, Scrawl } from '~/components/paper'
import { BRAND } from '../../../../packages/shared/src/brand'
import { Head } from './seo'
import { Section } from './site-parts'

const SECTIONS: { title: string; body: string[] }[] = [
  {
    title: 'The service',
    body: [
      `${BRAND.name} is an app, made by ${BRAND.company}, in which a child tells a story out loud and it is drawn on the screen and saved as a picture book. These terms cover the app and this website.`,
    ],
  },
  {
    title: 'Minutes',
    body: [
      'The app runs on minutes of storytelling. Minutes are prepaid credits: they have no cash value, cannot be exchanged for cash, and do not expire while the service runs. If we ever have to shut the service down, we will give reasonable notice.',
    ],
  },
  {
    title: 'Buying in the app',
    body: [
      'Packs of minutes bought inside the app are sold by Apple, and Apple’s terms and refund process apply to those purchases.',
    ],
  },
  {
    title: 'Buying on the web',
    body: [
      `Packs and gift codes bought on this website are handled by our payment processor. A web pack is refundable within 14 days if its minutes are unused; write to ${BRAND.supportEmail}.`,
    ],
  },
  {
    title: 'Gift codes',
    body: [
      'A gift code adds minutes to one family account when it is redeemed. Each code can be redeemed once. Codes have no cash value and cannot be resold.',
    ],
  },
  {
    title: 'Acceptable use',
    body: [
      'Use the app as intended, for a child’s own storytelling. Don’t try to break, overload, or abuse the service, resell access, or use it to create content that is unlawful or harmful.',
    ],
  },
  {
    title: 'Children and parents',
    body: [
      'The account holder is the parent or guardian, who is responsible for how the app is used. The app is meant to be used with a grown-up’s permission, and purchases sit behind a grown-up gate.',
    ],
  },
  {
    title: 'AI-generated content',
    body: [
      'The drawings are generated by an AI model from the child’s spoken words. Results vary, and the model is guided to skip ideas that are not suitable for a children’s picture book.',
    ],
  },
  {
    title: 'Liability',
    body: [
      'The service is provided as is. To the extent the law allows, we are not liable for indirect or incidental losses, and our total liability is limited to what you paid us in the prior twelve months.',
    ],
  },
  {
    title: 'Changes',
    body: [
      'We may update these terms as the product changes. If a change is significant, we will note it here with a new date.',
    ],
  },
  {
    title: 'Contact',
    body: [`Questions about these terms go to ${BRAND.supportEmail}.`],
  },
]

export function TermsPage() {
  return (
    <>
      <Head title="Terms" />
      <Section title="Terms" headingClassName="text-4xl md:text-5xl text-ink">
        <p className="font-hand text-lg text-ink-soft">Last updated 2026-09-22</p>
        <div className="mt-6 flex flex-col gap-4">
          {SECTIONS.map((s, i) => (
            <PaperCard key={s.title} tilt={i % 2 === 0 ? -0.6 : 0.6}>
              <Scrawl as="h2" className="text-2xl text-ink">
                {i + 1}. {s.title}
              </Scrawl>
              {s.body.map((p) => (
                <p key={p} className="mt-2 font-hand text-lg text-ink">
                  {p}
                </p>
              ))}
            </PaperCard>
          ))}
        </div>
      </Section>
    </>
  )
}
